function LanguageControllerEN()
{
	this.language = {
			tree : {			
				"typicalApplication" : "TypicalApplication",
				
				"CTD" : "CTD",
				"createCTD" : "createCTD",
				
				"addressBook" : "addressBook",									
				"addAccount" : "addAccount",				
				"queryAccount" : "queryAccount",	
			},

			titles : {
				"om" : "eSDK UC2.2 BS Demo",
				"language" : "Language",
				"description" : "Description",
				"execution" : "Execution",
				"sourceCode" : "Source code",
				
				"createCTDFunction" : "Interface fuction",
				"createCTDFunctionDesc" : "This is used to make a CTD call",
				"createCTDAccess" : "Access path",
				"createCTDAccessDesc" : "http://{ip}:{port}/esdk/rest/uc/appserver/ctd",
				"createCTDRequestType" : "Requset type",
				"createCTDRequestTypeDesc" : "POST",
				"createCTDParamFormat" : "Parameters format",
				"createCTDParamFormatDesc" : "application/json;charset=UTF-8",
				
				"inputParameterDesc" : "Input parameters description:",
				"outputParameterDesc" : "Output parameters description:",
				"resultCodeDesc" : "Result message code, zero is successful, other code reference API doc",
				"resultContextDesc" : "Result message, for displaying success and failed infomation",
				
				"resultDesc" : "Account ID is returned after successfully added",
				
				"accountParam" : "UC account:",
				"callerParam" : "Calling number:",
				"calleeParam" : "Called number:",
				"createCTD" : "makeCTDCall",
				"input" : "Input:",
				"output" : "Output:",
				"resultCode" : "Result code:",
				"resultContext" : "Result message:",
				
				"inputParameter" : "Parameter",
				"inputType" : "Data type",
				"inputRestriction" : "Restriction",
				"inputDescription" : "Description",
				"accountParamDesc" : "UC account which logined by mobile phone",
				"callerParamDesc" : "Calling number",
				"calleeParamDesc" : "Called number",
				
				"accountNull" : "UC account can not be null",
				"callerNull" : "Calling number can not be null",
				"calleeNull" : "Called number can not be null",
				
				"addAccountFunctionDesc" : "This interface is used to add an account",
				"addAccountAccessDesc" : "http://{ip}:{port}/esdk/rest/uc/bmu/account",
				"addAccountRequestTypeDesc" : "POST",
				
				"userIdParam" : "Operation user ID:",
				"accountTypeParam" : "Account type:",
				"loginNameParam" : "Login name:",
				"passwordParam" : "Login password:",
				"nameParam" : "User name:",
				"sexParam" : "User gender:",
				"homePhoneParam" : "Home phone:",
				"cellPhoneParam" : "Mobile number:",
				"officePhoneParam" : "Office phone:",
				"shortPhoneParam" : "Short number:",
				"otherPhoneParam" : "Other phone:",
				"faxParam" : "Fax:",
				"emailParam" : "Email:",
				"addrParam" : "Contact address:",
				"titleParam" : "Position:",
				"departmentIdParam" : "Department ID:",
				"userLevelParam" : "User account level ID:",
				"roleIdParam" : "User account role ID:",
				
				"addAccount" : "Add account",
				"result" : "result:",
				
				"userIdParamDesc" : "Operation user ID,for example:“12345”",
				"accountTypeParamDesc" : "Account type:0:Ordinary account2:UC account",
				"loginNameParamDesc" : "Login name,for example:“uc001”",
				"passwordParamDesc" : "Login password This password is required to log password using AES128 (using the negotiated work key) encryption algorithm and using BASE64 encoding.",
				"nameParamDesc" : "Login name,for example:“uc_test”",
				"sexParamDesc" : "User gender:Male:Male Female:Female",
				"homePhoneParamDesc" : " Home phone,for example:“87654321”",
				"cellPhoneParamDesc" : "Mobile number,for example:“13812345678”",
				"officePhoneParamDesc" : "Office phone,for example:“81234567”",
				"shortPhoneParamDesc" : "Short number,for example:“54321”",
				"otherPhoneParamDesc" : "Other phone,for example:“812356789”",
				"faxParamDesc" : "Fax,for example:“81234568”",
				"emailParamDesc" : "Email,for example:“a@b.com”",
				"addrParamDesc" : "Contact address,for example:“china.shenzhen”",
				"titleParamDesc" : "Position,for example:“manager”",
				"departmentIdParamDesc" : "UC account attribution department ID, you can get the department ID by querying the department,for example:“1000”",
				"userLevelParamDesc" : "UC account the level of ID, you can get the level of ID by querying the user level,for example:“1”",
				"roleIdParamDesc" : "UC account the role ID, you can get character ID by querying the role,for example:“1”",
				
				"userIdNull" : "Operation user ID can not be empty",
				"accountTypeNull" : "Account type can not be empty",
				"loginNameNull" : "Login name can not be empty",
				"passwordNull" : "Password can not be empty",
				"nameNull" : "User name can not be empty",
				"departmentIdNull" : "Department ID can not be empty",
				"userLevelNull" : "User account Level ID can not be empty",
				"roleIdNull" : "User account Roles ID can not be empty",
				
				"queryAccountFunctionDesc" : "This interface is used to query the account",
				"queryAccountAccessDesc" : "http://{ip}:{port}/esdk/rest/uc/bmu/account",
				"queryAccountRequestTypeDesc" : "GET",	
				
				"userIdParam" : "Operation user ID:",
				"exactSearchParam" : "Is accurate query:",
				"conditionParam" : "Query conditions:",
				"pageCountParam" : "Number of pages:",
				"pageNumParam" : "Current page:",
				
				"accountIdParam" : "Account ID:",	
				"bindNumParam" : "Binding SIP number:",
				
				"queryAccount" : "Query account",
				
				"exactSearchParamDesc" : "Is accurate query: 0: No 1: Yes Description: precise query returns only one record, returns an error code when more than one query records.",
				"conditionParamDesc" : "Query, only supported by “UC Account” query, for example:“uc”",
				"pageCountParamDesc" : "Number of pages paged query(0<pagecount<100)",
				"pageNumParamDesc" : "Current Page",
				
				"amountDesc" : "The total number of accounts in line with the conditions.",
				"accountsDesc" : "UC list of accounts.",
				"accountIdParamDesc" : "Account ID, account ID as a parameter to return when adding accounts.",
				"bindNumParamDesc" : " Binding of SIP number",
				
				"userIdNull" : "Operation user ID can not be empty",
				"exactSearchNull" : "Is accurate query can not be empty",
				"conditionNull" : "Query conditions can not be empty",
				"pageCountNull" : "The number of pages can not be empty",
				"pageNumNull" : "The current page can not be empty",
				
				"amount" : "Returns the total number of accounts:",
				"accounts" : "Returns uc account List",
				"accountType" : "Returns account Type:", 
				"accountId" : "Returns account ID:",
				"loginName" : "Returns login account:",
				"name" : "Returns the user name:",
				"sex" : "Returns gender:",
				"homePhone" : "Returns home phone:", 
				"cellPhone" : "Returns phone:", 
				"officePhone" : "Return to office:",
				"shortPhone" : "Returns cornet:", 
				"otherPhone" : "Returns other phone:", 
				"fax" : "Returns aax:", 
				"email" : "Returns Email:", 
				"addr" : "Back aontact address:",
				"title" : "Returns duties:", 
				"departmentId" : "Return to the home department account ID:",
				"userLevel" : "Returns account Level ID:", 
				"roleId" : "Returns account Role ID:",
				"bindNum" : "Returns SIP number:",
				
				"accountDesc" : "The total number of accounts qualified",
				"accountTypeDesc" : "Account type: 0: Normal Account 2: UC Account",
				"accountIdDesc" : "Account ID",
				"loginNameDesc" : "Login account",
				"nameDesc" : "User name",
				"sexDesc" : "Gender",
				"homePhoneDesc" : "Home phone", 
				"cellPhoneDesc" : "Cell phone",
				"officePhoneDesc" : "Office Phone",
				"shortPhoneDesc" : "Short number",
				"otherPhoneDesc" : "Other phone", 
				"faxDesc" : "Fax", 
				"emailDesc" : "Email",
				"addrDesc" : "Contact address",
				"titleDesc" : "Position", 
				"departmentIdDesc" : "Account attributable department ID",
				"userLevelDesc" : "Account level ID",
				"roleIdDesc" : "Account role ID",
				"bindNumDesc" : "SIP account number is bound to UC",
				
				"operationSuccess" : "Operation succeeded",
				"operationFailed" : "Operation failed",
				"userAuthFailed" : "User authricated failed",
				
				"sourceCodeDesc" : "The red color and bold fonts are codes of interface, other color is simulated to IDE tool, for easy reading.",
				
				"descriptionUC" : "eSDK Server supports all interfaces of UC2.2 service. eSDK provides Rest service，ISV can implement all UC function by sending Rest message",
				"copyright" : "Copyright © Huawei Technologies Co., Ltd. 1998-2015. All rights reserved"
			}
		};
}